In [1]:
import pandas as pd
import numpy as np

In [2]:
columns = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Species']
df = pd.read_csv("D:\pict\DSBDAPractical\DSBDALExam DataSets\Iris\Iris.csv", header=None, names = columns)
df.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth      Species
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [3]:
df.isnull().sum()

SepalLength    0
SepalWidth     0
PetalLength    0
PetalWidth     0
Species        0
dtype: int64

In [4]:
df.replace("?", np.nan, inplace=True)

In [6]:
cols = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth']

df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')

In [7]:
df.dropna(inplace=True)

In [8]:
df = df[(df[cols] > 0).all(axis=1)]
df.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth      Species
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [9]:
Q1 = df[cols].quantile(0.25)
Q3 = df[cols].quantile(0.75)

IQR = Q3 - Q1

df_clean = df[~((df[cols] < (Q1 - 1.5 * IQR)) | (df[cols] > (Q3 + 1.5 * IQR))).any(axis=1)]

df_clean.shape

(146, 5)

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df_scaled = df_clean.copy()
df_scaled[cols] = scaler.fit_transform(df_clean[cols])

df_scaled.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth      Species
0    -0.910515    1.175789    -1.374878   -1.345899  Iris-setosa
1    -1.151122   -0.093924    -1.374878   -1.345899  Iris-setosa
2    -1.391729    0.413961    -1.431986   -1.345899  Iris-setosa
3    -1.512032    0.160019    -1.317771   -1.345899  Iris-setosa
4    -1.030819    1.429732    -1.374878   -1.345899  Iris-setosa

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df_scaled['Species'] = le.fit_transform(df_scaled['Species'])
df_scaled.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth  Species
0    -0.910515    1.175789    -1.374878   -1.345899        0
1    -1.151122   -0.093924    -1.374878   -1.345899        0
2    -1.391729    0.413961    -1.431986   -1.345899        0
3    -1.512032    0.160019    -1.317771   -1.345899        0
4    -1.030819    1.429732    -1.374878   -1.345899        0

In [12]:
from sklearn.model_selection import train_test_split

X = df_scaled[cols]
y = df_scaled['Species']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

lr = LogisticRegression()

lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

acc_lr = accuracy_score(y_test, y_pred_lr)
print("Logistic Regression Accuracy:", acc_lr)

Logistic Regression Accuracy: 0.9333333333333333

In [14]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()

nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)

acc_nb = accuracy_score(y_test, y_pred_nb)
print("Naïve Bayes Accuracy:", acc_nb)

Naïve Bayes Accuracy: 0.9333333333333333

In [16]:
from sklearn.neighbors import KNeighborsClassifier

# Create model
knn = KNeighborsClassifier(n_neighbors=3)

# Train model
knn.fit(X_train, y_train)

# Predict test data
y_pred_knn = knn.predict(X_test)

# Accuracy score
acc_knn = accuracy_score(y_test, y_pred_knn)

print("KNN Accuracy:", acc_knn)

KNN Accuracy: 0.9333333333333333

In [17]:
print("Model Accuracy Comparison")
print("-------------------------")

print("Logistic Regression:", acc_lr)
print("Naïve Bayes:", acc_nb)
print("KNN:", acc_knn)

Model Accuracy Comparison
-------------------------
Logistic Regression: 0.9333333333333333
Naïve Bayes: 0.9333333333333333
KNN: 0.9333333333333333