In [1]:
import pandas as pd

In [7]:
columns = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Species']
df = pd.read_csv("D:\pict\DSBDAPractical\DSBDALExam DataSets\Iris\Iris.csv", header=None, names = columns)
df.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth      Species
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [8]:
print(df.shape)
print(df.columns)

df.info()

(150, 5)
Index(['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Species'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SepalLength  150 non-null    float64
 1   SepalWidth   150 non-null    float64
 2   PetalLength  150 non-null    float64
 3   PetalWidth   150 non-null    float64
 4   Species      150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [9]:
list(df['Species'].unique())

['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

In [11]:
setosas = df[df['Species'] == 'Iris-setosa']
display(setosas.head())

versicolors = df[df['Species'] == 'Iris-versicolor']
display(versicolors.head())

   SepalLength  SepalWidth  PetalLength  PetalWidth      Species
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

    SepalLength  SepalWidth  PetalLength  PetalWidth          Species
50          7.0         3.2          4.7         1.4  Iris-versicolor
51          6.4         3.2          4.5         1.5  Iris-versicolor
52          6.9         3.1          4.9         1.5  Iris-versicolor
53          5.5         2.3          4.0         1.3  Iris-versicolor
54          6.5         2.8          4.6         1.5  Iris-versicolor

In [13]:
merged_data = pd.concat([setosas, versicolors])
display(merged_data.head())
print(merged_data.shape)

   SepalLength  SepalWidth  PetalLength  PetalWidth      Species
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

(100, 5)

In [14]:
sorted_petals = df.sort_values(by = 'PetalLength') # , ascending = False
display(sorted_petals.head())

    SepalLength  SepalWidth  PetalLength  PetalWidth      Species
22          4.6         3.6          1.0         0.2  Iris-setosa
13          4.3         3.0          1.1         0.1  Iris-setosa
14          5.8         4.0          1.2         0.2  Iris-setosa
35          5.0         3.2          1.2         0.2  Iris-setosa
36          5.5         3.5          1.3         0.2  Iris-setosa

In [16]:
transposed_df = df.T
display(transposed_df.head())

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
SepalLength,5.1,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,...,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
SepalWidth,3.5,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,...,3.1,3.1,2.7,3.2,3.3,3.0,2.5,3.0,3.4,3.0
PetalLength,1.4,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,...,5.6,5.1,5.1,5.9,5.7,5.2,5.0,5.2,5.4,5.1
PetalWidth,0.2,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,...,2.4,2.3,1.9,2.3,2.5,2.3,1.9,2.0,2.3,1.8
Species,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,...,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica

In [21]:
melted_data = pd.melt(
    df,
    id_vars = ['Species'],
    var_name = 'Measurement',
    value_name = 'Value'
)
display(melted_data.head())

       Species  Measurement  Value
0  Iris-setosa  SepalLength    5.1
1  Iris-setosa  SepalLength    4.9
2  Iris-setosa  SepalLength    4.7
3  Iris-setosa  SepalLength    4.6
4  Iris-setosa  SepalLength    5.0

In [23]:
melted_data['ID'] = melted_data.index
wide_data = melted_data.pivot_table(
    index='ID',
    columns='Measurement',
    values='Value',
    aggfunc='first'
)
display(wide_data.head())

Measurement  PetalLength  PetalWidth  SepalLength  SepalWidth
ID
0                    NaN         NaN          5.1         NaN
1                    NaN         NaN          4.9         NaN
2                    NaN         NaN          4.7         NaN
3                    NaN         NaN          4.6         NaN
4                    NaN         NaN          5.0         NaN